#cloud-config

# Set Hostname
hostname: CoreOS_BM

# Set SSH Keys
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC30vQko0K/jwNxKq7U/CbuL3mH71tEOwpkHQfQglUAXRdHAEk5yansr/zKhNdxu1XJ7gUMcF/0iZ1IZQbEV9MMEm1Xgk6i3uIRWHKYNajWGjAVDtsuw4ljK9pEIczdLEApdgGUPct7ngI8rj+0gh57Jr543MrcXLesvg19xlOWVUvTRjPOUrmNzpbl5AzDzAOS8mJux+RPTeyIgAA6CM5KD8fpBtEha+vMVFSflJ3oMwHcevVd6KvfxdahwdwHLG5J0ZW3PENZ1RUe7UmpZWhFPEpbfxlX2kXcFLz86ZH+L1ddG8RcnNfjmb8m3V/jLlVi6NSFWAPzfWq7IHmSUg7L jcastrof@MacBook-Pro-de-Arturo-2.local

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    https://discovery.etcd.io/73c2f183d0c5cb888c18e1c02b9ee010
