#cloud-config

hostname: kb8-master

coreos:
  etcd:    
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: static.network
      content: |
        [Match]
        Name=ens3

        [Network]
        Address=192.168.0.15/24
        Gateway=192.168.0.1
users:
  - name: core
    ssh-authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMxWrt0g5OznsB5FYzS+xnozoNrlTYGFMq7OXIgz3Ie+XSxDjT4Pi2PUx1gt1FAYGKkyxviEkVtC5I/OatMtgaQMdiToEHX7+B7psZpk1x2EWp/+coQKmBs2sD6QDWRwRIkPJgk4InH80FgIcgoMDe55o0PyOOjZSoW0/qs9ahgjfT/LHEBpWD6+Yw+vXbjHYC2EUUHltpn9RYL2tKe3Dj94gNrJS4OW1KVaWEC4nNViKpPC9j7dJJ6dESZz8Jkzra9geDzh6jMbTIleljx53JOEUrRCspK3SSUKE1wna1Zy6bDNacc5MUYlHXX30Ah4TsWilF7aHEe/K6ISb3olB7 jcastrof@MacBook-Pro-de-Arturo-2.local
  - groups:
      - sudo
      - docker